version: 1
services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - port: 3001
        target_port: 3001
    envs:
      - from_file: .env
    depends_on:
      - db
    restart: always
    network: mynetwork # Используем созданную сеть Docker

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - port: 3000
        target_port: 3000
    depends_on:
      - backend
    network: mynetwork # Используем созданную сеть Docker

  db:
    image: postgres:15
    envs:
      - from_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Нет необходимости в ports в Amvera, если только не хотите делать БД доступной извне
    network: mynetwork # Используем созданную сеть Docker

volumes:
  postgres_data:

network:
  mynetwork: # Создаем сеть Docker для взаимодействия между контейнерами
