FROM node:20

WORKDIR /app

# Копируем ТОЛЬКО package.json сначала для кэширования
COPY package.json ./

RUN npm install

# Копируем остальные файлы
COPY . .

WORKDIR /app/frontend

EXPOSE 3000
CMD ["npm", "run", "serve"]