version: "3.8"

services:
  backend:
    build:
      context: .
      target: backend # Указываем, какой этап билда использовать
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - mynetwork

  frontend:
    build:
      context: .
      target: frontend # Указываем, какой этап билда использовать
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432" # УДАЛЕНИЕ этого порта сделает базу данных доступной только внутри сети Docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork: # Создаем сеть Docker для взаимодействия между контейнерами
