FROM node:20

WORKDIR /app

# Копируем ТОЛЬКО package.json сначала для кэширования
COPY package.json package-lock.json ./

RUN npm install

# Копируем остальные файлы
COPY . .

WORKDIR /app/backend

EXPOSE 3001
CMD ["sh", "-c", "npm run db:init && npm run start"]
